# Generated by Django 5.2.7 on 2025-11-03 11:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(blank=True, max_length=50)),
                ('club', models.CharField(blank=True, max_length=100)),
                ('liga', models.CharField(blank=True, max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('JUG', 'Jugador de campo'), ('POR', 'Portero')], editable=False, max_length=3)),
                ('posicion', models.CharField(choices=[('POR', 'Portero'), ('DFC', 'Defensa Central'), ('LTI', 'Lateral Izquierdo'), ('LTD', 'Lateral Derecho'), ('MC', 'Medio Centro'), ('MI', 'Medio Izquierdo'), ('MD', 'Medio Derecho'), ('DC', 'Delantero Centro'), ('MP', 'Media Punta')], max_length=3)),
                ('valoracion_general', models.IntegerField(default=1, editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-valoracion_general', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartaJugador',
            fields=[
                ('carta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion.carta')),
                ('ritmo', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('tiro', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('pase', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('regate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('defensa', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('fisico', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
            ],
            bases=('gestion.carta',),
        ),
        migrations.CreateModel(
            name='CartaPortero',
            fields=[
                ('carta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion.carta')),
                ('estirada', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('paradas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('saque', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('reflejos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('velocidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('colocacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
            ],
            bases=('gestion.carta',),
        ),
        migrations.AddConstraint(
            model_name='carta',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('posicion', 'POR'), ('tipo', 'POR')), models.Q(('tipo', 'POR'), _negated=True), _connector='OR'), name='tipo_por_pos_por'),
        ),
        migrations.AddConstraint(
            model_name='carta',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'JUG'), models.Q(('posicion', 'POR'), _negated=True)), models.Q(('tipo', 'JUG'), _negated=True), _connector='OR'), name='tipo_jug_pos_no_por'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='cartas',
            field=models.ManyToManyField(blank=True, to='gestion.carta'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='equipo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.equipo'),
        ),
    ]
