# Generated by Django 5.2.7 on 2025-11-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
