# Generated by Django 5.2.7 on 2025-11-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_carta_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='valoracion_general',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='cartajugador',
            name='defensa',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cartajugador',
            name='fisico',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cartajugador',
            name='pase',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cartajugador',
            name='regate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cartajugador',
            name='ritmo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cartajugador',
            name='tiro',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cartaportero',
            name='colocacion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cartaportero',
            name='estirada',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cartaportero',
            name='paradas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cartaportero',
            name='reflejos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cartaportero',
            name='saque',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cartaportero',
            name='velocidad',
            field=models.IntegerField(),
        ),
    ]
