# Generated by Django 5.2.7 on 2025-11-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_carta_valoracion_general_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='cartas',
            field=models.ManyToManyField(blank=True, related_name='equipos', to='gestion.carta'),
        ),
    ]
