# Generated by Django 5.2.7 on 2025-11-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_equipo_cartas'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='media',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
